export const dat = [
    {
        firstName: "Adam",
        lastName: "Levine",
        id: 1,
        bureau: "Agriculture",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Louis",
        lastName: "Vuitton",
        id: 2,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Adnan",
        lastName: "Ahmad",
        id: 3,
        bureau: "Culture",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Ankit",
        lastName: "sharma",
        id: 4,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Rafal",
        lastName: "Nadal",
        id: 5,
        bureau: "Culture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Holi",
        lastName: "Hai",
        id: 6,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Khali",
        lastName: "Bali",
        id: 7,
        bureau: "Skills",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Judge",
        lastName: "Fudge",
        id: 8,
        bureau: "Karate",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Ted",
        lastName: "Mosby",
        id: 9,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Robin",
        lastName: "Schrebartsky",
        id: 10,
        bureau: "Karate",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Lilly",
        lastName: "Aldrin",
        id: 11,
        bureau: "Skills",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Barney",
        lastName: "Stinson",
        id: 12,
        bureau: "Agriculture",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Ranjeet",
        lastName: "Singh",
        id: 13,
        bureau: "Culture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Mark",
        lastName: "David",
        id: 14,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Tracy",
        lastName: "Maccone",
        id: 15,
        bureau: "Karate",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Bhawna",
        lastName: "Manot",
        id: 16,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Hary",
        lastName: "Kane",
        id: 17,
        bureau: "Skills",
        eventCreationAccess: false,
        roleAssigned: "canteen",
    },
    {
        firstName: "Andy",
        lastName: "Bernard",
        id: 18,
        bureau: "Agriculture",
        eventCreationAccess: false,
        roleAssigned: null,
    },
    {
        firstName: "Michael",
        lastName: "Scott",
        id: 19,
        bureau: "Culture",
        eventCreationAccess: true,
        roleAssigned: null,
    },
    {
        firstName: "Sachin",
        lastName: "Lol",
        id: 20,
        bureau: "Skill",
        eventCreationAccess: true,
        roleAssigned: null,
    },
]